### PR TITLE
chore: update airflow to 2.5.3

### PR DESCRIPTION
**Pull request by vyeshwanth**
## Description
- Update airflow version to 2.5.3

## Testing validation
```
[2023-04-26, 12:26:14 UTC] {base.py:73} INFO - Using connection ID 'rudderstack_default' for task execution.
[2023-04-26, 12:26:14 UTC] {rudderstack.py:76} INFO - got connection
[2023-04-26, 12:26:14 UTC] {rudderstack.py:31} INFO - triggering sync for sourceId: 2Ov8fmGFB9Mu6NmsBsTBKvJS00U, endpoint: /v2/sources/2Ov8fmGFB9Mu6NmsBsTBKvJS00U/start
[2023-04-26, 12:26:15 UTC] {base.py:73} INFO - Using connection ID 'rudderstack_default' for task execution.
[2023-04-26, 12:26:17 UTC] {rudderstack.py:34} INFO - 200
[2023-04-26, 12:26:17 UTC] {rudderstack.py:36} INFO - Job triggered for sourceId: 2Ov8fmGFB9Mu6NmsBsTBKvJS00U
[2023-04-26, 12:26:17 UTC] {base.py:73} INFO - Using connection ID 'rudderstack_default' for task execution.
[2023-04-26, 12:26:17 UTC] {rudderstack.py:76} INFO - got connection
[2023-04-26, 12:26:17 UTC] {base.py:73} INFO - Using connection ID 'rudderstack_default' for task execution.
[2023-04-26, 12:26:21 UTC] {rudderstack.py:53} INFO - sync status for sourceId: 2Ov8fmGFB9Mu6NmsBsTBKvJS00U, status: finished
[2023-04-26, 12:26:21 UTC] {rudderstack.py:60} INFO - sync finished for sourceId: 2Ov8fmGFB9Mu6NmsBsTBKvJS00U
[2023-04-26, 12:26:21 UTC] {taskinstance.py:1332} INFO - Marking task as SUCCESS. dag_id=rudderstack-sample, task_id=rs-trigger-sync, execution_date=20230426T122551, start_date=20230426T122610, end_date=20230426T122621
[2023-04-26, 12:26:23 UTC] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-04-26, 12:26:24 UTC] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
```
## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
## Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added unit tests for the code
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by AchuthaSourabhC — APPROVED** [review]

**Comment by AchuthaSourabhC** [comment]
Anyway to test and confirm all is good after the update ?

**Comment by AchuthaSourabhC** [comment]
We would also need to confirm if snyk vulnerability is actually resolved after this

**Comment by AchuthaSourabhC** [comment]
Can we change this line in readme `trigger your [Reverse ETL](https://www.rudderstack.com/docs/reverse-etl) syncs` since now you can use for ETL too

**Comment by vyeshwanth** [comment]
> We would also need to confirm if snyk vulnerability is actually resolved after this

https://app.snyk.io/org/subbu-utx/pr-checks/f915020b-e33d-4baa-8a80-07f7c106a331

**Review by RanjeetMishra — APPROVED** [review]
LGTM
Can you run command to update requirements.txt, for me it also added `requests==2.25.1`

Also we can improve the test code for wait. Once this PR gets merged, I can raise PR from another one where I added test for wait and then finish.
https://github.com/rudderlabs/rudder-airflow-provider/pull/10

**Comment by vyeshwanth** [comment]
> Can you run command to update requirements.txt, for me it also added requests==2.25.1

@RanjeetMishra we import requests in the test code. let me add it. we don't need it in the `setup.cfg` though.

**Pull request merged**
